### ISSUE TITLE
[BUG] Visual display issues with empty content.

### ISSUE THREAD

**Issue by TechCrafterGaming** [CyanVoxel/TagStudio#17] opened 2024-04-23 14:46 UTC
I believe it’s not supposed to look like this normally. I’m not sure if I caused the error myself…

In the image below, you can see that the empty fields are not loading correctly, this also happened when there was nothing in the library. Maybe it’s an idea not to display them, then if the whole area is empty, you could display a specific text like ‘please open a library’ or something like that.

![image](https://github.com/CyanVoxel/TagStudio/assets/67552605/6d81f453-d84f-4e7c-8197-984c783eb2d0)

**Comment by CyanVoxel** [comment] 2024-04-23 18:33
The empty fields on startup have been fixed in PR #22 . However I'm not sure if that alsos fixes this issue for libraries that are already loaded, and I can't reproduce the issue myself. Would you mind seeing if the issue still persists on the updated version?

**Comment by Thesacraft** [comment] 2024-04-23 18:36
This is also fixed by #22 i think, as seen here:
![grafik](https://github.com/CyanVoxel/TagStudio/assets/91694323/e888efa4-760f-408e-9543-e43e5f19f5f2)

**Comment by CyanVoxel** [comment] 2024-04-23 18:39
Sweet, I'll go ahead and close this then 👍

**Closed by CyanVoxel** 2024-04-23 18:39 UTC
Labels: bug
